apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html-as
data:
  index.html: |
    <html>
    <head><title>AS - Cluster1</title></head>
    <body>
      <h1>Hello from <b>AS - Cluster1 (kind-cluster1)</b>!</h1>
    </body>
    </html>

