apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head><title>Cluster1</title></head>
    <body>
      <h1>Hello from <b>Cluster1 (kind-cluster1)</b>!</h1>
    </body>
    </html>
