apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: as-nginx
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: cluster1
        url: https://kubernetes.default.svc
      - cluster: cluster2
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{.cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/manyb2ns/argocd.git
        targetRevision: main
        path: application_sets/templates/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: default