apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: as-nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: kind-cluster1
      - cluster: kind-cluster2
  template:
    metadata:
      name: '{{.cluster}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/manyb2ns/argocd.git
        targetRevision: main
        path: application_sets/templates/{{.cluster}}
      destination:
        name: '{{.cluster}}'
        namespace: default