apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx-deploy.yaml

configMapGenerator:
  - name: nginx-html
    files:
      - nginx-config/index.html

generatorOptions:
  disableNameSuffixHash: false
