apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-html
data:
  index.html: |
    <html>
    <head><title>Cluster2</title></head>
    <body>
      <h1>Hello from <b>Cluster2 (kind-cluster2)</b>!</h1>
      <h1>Test Comment 2512041537</h1>
    </body>
    </html>
